version: 0.2
phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source ~/.cargo/env
      - rustup default 1.90.0
      - cargo install sqlx-cli --no-default-features --features postgres
  pre_build:
    commands:
      - docker run -d --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=password postgres:13
      - sleep 15
      - export DATABASE_URL=postgres://postgres:password@localhost:5432/postgres
      - sqlx migrate run
  build:
    commands:
      - cargo build --release
      - cargo test
artifacts:
  files:
    - target/release/zero2prod
  name: zero2prod-$(date +%Y-%m-%d)
