version: 0.2
phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source ~/.cargo/env
      - rustup default 1.90.0
  build:
    commands:
      - cargo build --release
      - cargo test
