apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero2prod
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: zero2prod
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
