apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero2prod
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: zero2prod
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
